
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '63A36E98273E4424E19D7B77D42ED059'
    
_lr_action_items = {'STRING':([0,10,11,20,22,23,],[5,5,18,5,18,5,]),'NUMBER':([0,10,20,23,],[6,6,6,6,]),'TRUE':([0,10,20,23,],[7,7,7,7,]),'FALSE':([0,10,20,23,],[8,8,8,8,]),'NULL':([0,10,20,23,],[9,9,9,9,]),'CORCHEIZQ':([0,10,20,23,],[10,10,10,10,]),'LLAVEIZQ':([0,10,20,23,],[11,11,11,11,]),'$end':([1,2,3,4,5,6,7,8,9,12,15,19,21,],[0,-1,-11,-12,-13,-14,-15,-16,-17,-7,-2,-8,-3,]),'COMA':([3,4,5,6,7,8,9,12,14,15,17,19,21,26,],[-11,-12,-13,-14,-15,-16,-17,-7,20,-2,22,-8,-3,-6,]),'CORCHEDER':([3,4,5,6,7,8,9,10,12,13,14,15,19,21,24,],[-11,-12,-13,-14,-15,-16,-17,12,-7,19,-10,-2,-8,-3,-9,]),'LLAVEDER':([3,4,5,6,7,8,9,11,12,15,16,17,19,21,25,26,],[-11,-12,-13,-14,-15,-16,-17,15,-7,-2,21,-4,-8,-3,-5,-6,]),'DOSPUNTOS':([18,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'first':([0,],[1,]),'value':([0,10,20,23,],[2,14,14,26,]),'array':([0,10,20,23,],[3,3,3,3,]),'object':([0,10,20,23,],[4,4,4,4,]),'elements':([10,20,],[13,24,]),'members':([11,22,],[16,25,]),'pair':([11,22,],[17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> first","S'",1,None,None,None),
  ('first -> value','first',1,'p_first','tptleng.py',46),
  ('object -> LLAVEIZQ LLAVEDER','object',2,'p_object','tptleng.py',55),
  ('object -> LLAVEIZQ members LLAVEDER','object',3,'p_object','tptleng.py',56),
  ('members -> pair','members',1,'p_members','tptleng.py',67),
  ('members -> pair COMA members','members',3,'p_members','tptleng.py',68),
  ('pair -> STRING DOSPUNTOS value','pair',3,'p_pair','tptleng.py',80),
  ('array -> CORCHEIZQ CORCHEDER','array',2,'p_array','tptleng.py',87),
  ('array -> CORCHEIZQ elements CORCHEDER','array',3,'p_array','tptleng.py',88),
  ('elements -> value COMA elements','elements',3,'p_elements','tptleng.py',99),
  ('elements -> value','elements',1,'p_elements','tptleng.py',100),
  ('value -> array','value',1,'p_value_array','tptleng.py',111),
  ('value -> object','value',1,'p_value_object','tptleng.py',116),
  ('value -> STRING','value',1,'p_value_string','tptleng.py',121),
  ('value -> NUMBER','value',1,'p_value_number','tptleng.py',126),
  ('value -> TRUE','value',1,'p_value_true','tptleng.py',131),
  ('value -> FALSE','value',1,'p_value_false','tptleng.py',135),
  ('value -> NULL','value',1,'p_value_null','tptleng.py',139),
]
